import type {
  CollectionMovement,
  CrmCustomer,
  CustomerInvoiceRef,
} from "./crmCustomerTypes";
export const crmCustomers: CrmCustomer[] = [
  {
    id: "atlas-makine",
    name: "Atlas Makine Sanayi A.Ş.",
    type: "Tüzel Kişi",
    taxNo: "1234567890",
    phone: "+90 212 555 24 18",
    whatsapp: "+90 532 555 24 18",
    email: "muhasebe@atlasmakine.com",
    projects: ["Redüktör Modernizasyonu", "Dişli Revizyonu"],
    planned: "₺1.240.000",
    collected: "₺820.000",
    balance: "₺420.000",
    contact: "Mert Aydın",
    address: "İkitelli OSB, Başakşehir / İstanbul",
  },
  {
    id: "eksen-otomotiv",
    name: "Eksen Otomotiv Ltd.",
    type: "Tüzel Kişi",
    taxNo: "9876543210",
    phone: "+90 262 555 11 42",
    email: "finans@eksenotomotiv.com",
    projects: ["Konik Dişli Serisi"],
    planned: "₺486.500",
    collected: "₺300.000",
    balance: "₺186.500",
    contact: "Derya Koç",
    address: "Gebze OSB, Kocaeli",
  },
  {
    id: "selim-kaya",
    name: "Selim Kaya",
    type: "Gerçek Kişi",
    taxNo: "11122233440",
    phone: "+90 533 444 82 10",
    email: "selim.kaya@example.com",
    projects: ["Özel İmalat"],
    planned: "₺96.000",
    collected: "₺96.000",
    balance: "₺0",
    contact: "Selim Kaya",
    address: "Nilüfer / Bursa",
  },
];
export const customerFormDefaults = {
  companyName: "",
  personType: "Firma",
  taxNo: "",
  contact: "",
  taxOffice: "",
  phone: "",
  email: "",
  city: "",
  district: "",
  website: "",
  address: "",
  status: "Aktif",
  accountType: "Resmi Hesap",
  riskLimit: "",
  dueDays: "30",
  currency: "TRY",
  tags: "",
  notes: "",
};
export const officialCollectionMovements: CollectionMovement[] = [
  {
    date: "16.07.2026",
    title: "Redüktör siparişi tahsilatı",
    planned: "₺420.000",
    paid: "₺420.000",
    status: "Gerçekleşti",
    project: "Redüktör Modernizasyonu",
  },
  {
    date: "31.07.2026",
    title: "Proje ikinci hakediş",
    planned: "₺260.000",
    paid: "₺0",
    status: "Planlanan",
    project: "Dişli Revizyonu",
  },
  {
    date: "10.07.2026",
    title: "Geciken bakım tahsilatı",
    planned: "₺85.000",
    paid: "₺0",
    status: "Gecikmiş",
    project: "Dişli Revizyonu",
  },
];
export const officialAccountSummary = {
  planned: "₺1.240.000",
  collected: "₺820.000",
  balance: "₺420.000",
  overdue: "₺85.000",
  upcoming: "₺260.000",
  shares: [66, 7, 27],
};
export const unofficialAccountSummary = {
  planned: "₺185.000",
  collected: "₺65.000",
  balance: "₺120.000",
  overdue: "₺20.000",
  upcoming: "₺100.000",
  shares: [35, 11, 54],
};
export const unofficialCollectionMovements: CollectionMovement[] = [
  {
    date: "14.07.2026",
    title: "Prototip parça avansı",
    planned: "₺65.000",
    paid: "₺65.000",
    status: "Gerçekleşti",
    project: "Dişli Revizyonu",
  },
  {
    date: "05.08.2026",
    title: "Saha çalışması alacağı",
    planned: "₺100.000",
    paid: "₺0",
    status: "Planlanan",
    project: "Redüktör Modernizasyonu",
  },
  {
    date: "08.07.2026",
    title: "Teknik danışmanlık alacağı",
    planned: "₺20.000",
    paid: "₺0",
    status: "Gecikmiş",
    project: "Dişli Revizyonu",
  },
];
export const customerInvoiceRefs: CustomerInvoiceRef[] = [
  {
    type: "Satış Faturası",
    no: "FTR-2026-0718",
    date: "16.07.2026",
    due: "31.07.2026",
    amount: "₺420.000",
    status: "Onaylandı",
  },
  {
    type: "E-Fatura",
    no: "EFT-2026-0642",
    date: "02.06.2026",
    due: "02.07.2026",
    amount: "₺260.000",
    status: "Ödendi",
  },
  {
    type: "İade Faturası",
    no: "IA-2026-0018",
    date: "12.05.2026",
    due: "12.05.2026",
    amount: "-₺18.500",
    status: "Kapandı",
  },
];
export const crmSubmenu = [
  {
    id: "customers",
    label: "Müşteriler",
    route: "/apps/demo/crm/customers",
  },
];
