// AUTO-GENERATED offline governance artifact for Phase 2A (read-only/offline engineering).
// Mechanically derived from the Phase 1 audit's live-verified field extraction
// (docs/parasut/PARASUT_PROFESSIONAL_INTEGRATION_MASTER_PLAN.md §6/§14) — the same
// 401-attribute inventory pulled from supabase/migrations/20260723103525_...sql.
// This file defines the CANONICAL field-mapping registry: it is data only, never
// imported by the production sync/upsert path in Phase 2A. Do not wire this into
// server/parasut/upsert-resource.ts until Phase 2B is explicitly authorized.
//
// sourceLocation: "attributes" | "relationships" — which part of a Paraşüt JSON:API
// resource this field's data lives in. Matches the "_parasut_id" suffix / known
// relationship-array-container heuristic established in the Phase 1 audit.
//
// expectedPgType: the conversion kind deriveTypedRow (typed-row.ts) should use.
// currentlyMappedByProduction: true only for the 5 fields the live production
// upsert path actually writes today (contacts' 4 balance fields, sales_invoices'
// gross_total) — everything else is COLUMN_EXISTS_BUT_NOT_MAPPED per Phase 1.

export type FieldSourceLocation = "attributes" | "relationships";
export type FieldConversionKind = "text" | "boolean" | "numeric" | "timestamptz" | "date" | "jsonb";

export interface FieldMapping {
  resource: string;
  attribute: string;
  sourceLocation: FieldSourceLocation;
  expectedColumn: string;
  expectedPgType: FieldConversionKind;
  /** True only for fields the live production writer maps today (Phase 1, §6/§14). */
  currentlyMappedByProduction: boolean;
}

export const FIELD_MAPPING_REGISTRY: readonly FieldMapping[] = [
  { resource: "accounts", attribute: "used_for", sourceLocation: "attributes", expectedColumn: "used_for", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "last_used_at", sourceLocation: "attributes", expectedColumn: "last_used_at", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "balance", sourceLocation: "attributes", expectedColumn: "balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "last_adjustment_date", sourceLocation: "attributes", expectedColumn: "last_adjustment_date", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "bank_integration_type", sourceLocation: "attributes", expectedColumn: "bank_integration_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "associate_email", sourceLocation: "attributes", expectedColumn: "associate_email", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "account_type", sourceLocation: "attributes", expectedColumn: "account_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "bank_name", sourceLocation: "attributes", expectedColumn: "bank_name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "bank_branch", sourceLocation: "attributes", expectedColumn: "bank_branch", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "bank_account_no", sourceLocation: "attributes", expectedColumn: "bank_account_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "accounts", attribute: "iban", sourceLocation: "attributes", expectedColumn: "iban", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "total_paid", sourceLocation: "attributes", expectedColumn: "total_paid", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "remaining", sourceLocation: "attributes", expectedColumn: "remaining", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "remaining_in_trl", sourceLocation: "attributes", expectedColumn: "remaining_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "due_date", sourceLocation: "attributes", expectedColumn: "due_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "exchange_rate", sourceLocation: "attributes", expectedColumn: "exchange_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "bank_fees", attribute: "tags", sourceLocation: "relationships", expectedColumn: "tags", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "balance", sourceLocation: "attributes", expectedColumn: "balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "trl_balance", sourceLocation: "attributes", expectedColumn: "trl_balance", expectedPgType: "numeric", currentlyMappedByProduction: true },
  { resource: "contacts", attribute: "usd_balance", sourceLocation: "attributes", expectedColumn: "usd_balance", expectedPgType: "numeric", currentlyMappedByProduction: true },
  { resource: "contacts", attribute: "eur_balance", sourceLocation: "attributes", expectedColumn: "eur_balance", expectedPgType: "numeric", currentlyMappedByProduction: true },
  { resource: "contacts", attribute: "gbp_balance", sourceLocation: "attributes", expectedColumn: "gbp_balance", expectedPgType: "numeric", currentlyMappedByProduction: true },
  { resource: "contacts", attribute: "email", sourceLocation: "attributes", expectedColumn: "email", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "short_name", sourceLocation: "attributes", expectedColumn: "short_name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "contact_type", sourceLocation: "attributes", expectedColumn: "contact_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "tax_office", sourceLocation: "attributes", expectedColumn: "tax_office", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "tax_number", sourceLocation: "attributes", expectedColumn: "tax_number", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "district", sourceLocation: "attributes", expectedColumn: "district", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "postal_code", sourceLocation: "attributes", expectedColumn: "postal_code", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "city", sourceLocation: "attributes", expectedColumn: "city", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "country", sourceLocation: "attributes", expectedColumn: "country", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "address", sourceLocation: "attributes", expectedColumn: "address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "phone", sourceLocation: "attributes", expectedColumn: "phone", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "fax", sourceLocation: "attributes", expectedColumn: "fax", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "is_abroad", sourceLocation: "attributes", expectedColumn: "is_abroad", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "iban", sourceLocation: "attributes", expectedColumn: "iban", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "account_type", sourceLocation: "attributes", expectedColumn: "account_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "untrackable", sourceLocation: "attributes", expectedColumn: "untrackable", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "invoicing_preferences", sourceLocation: "relationships", expectedColumn: "invoicing_preferences", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "contact_portal_parasut_id", sourceLocation: "relationships", expectedColumn: "contact_portal_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "contacts", attribute: "contact_people", sourceLocation: "relationships", expectedColumn: "contact_people", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "uuid", sourceLocation: "attributes", expectedColumn: "uuid", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "vkn", sourceLocation: "attributes", expectedColumn: "vkn", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "invoice_number", sourceLocation: "attributes", expectedColumn: "invoice_number", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "note", sourceLocation: "attributes", expectedColumn: "note", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "is_printed", sourceLocation: "attributes", expectedColumn: "is_printed", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "status", sourceLocation: "attributes", expectedColumn: "status", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "printed_at", sourceLocation: "attributes", expectedColumn: "printed_at", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "cancellable_until", sourceLocation: "attributes", expectedColumn: "cancellable_until", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "is_signed", sourceLocation: "attributes", expectedColumn: "is_signed", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "e_archives", attribute: "sales_invoice_parasut_id", sourceLocation: "relationships", expectedColumn: "sales_invoice_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoice_inboxes", attribute: "vkn", sourceLocation: "attributes", expectedColumn: "vkn", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoice_inboxes", attribute: "e_invoice_address", sourceLocation: "attributes", expectedColumn: "e_invoice_address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoice_inboxes", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoice_inboxes", attribute: "inbox_type", sourceLocation: "attributes", expectedColumn: "inbox_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoice_inboxes", attribute: "address_registered_at", sourceLocation: "attributes", expectedColumn: "address_registered_at", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "e_invoice_inboxes", attribute: "registered_at", sourceLocation: "attributes", expectedColumn: "registered_at", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "external_id", sourceLocation: "attributes", expectedColumn: "external_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "uuid", sourceLocation: "attributes", expectedColumn: "uuid", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "env_uuid", sourceLocation: "attributes", expectedColumn: "env_uuid", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "from_address", sourceLocation: "attributes", expectedColumn: "from_address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "from_vkn", sourceLocation: "attributes", expectedColumn: "from_vkn", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "to_address", sourceLocation: "attributes", expectedColumn: "to_address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "to_vkn", sourceLocation: "attributes", expectedColumn: "to_vkn", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "direction", sourceLocation: "attributes", expectedColumn: "direction", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "note", sourceLocation: "attributes", expectedColumn: "note", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "response_type", sourceLocation: "attributes", expectedColumn: "response_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "contact_name", sourceLocation: "attributes", expectedColumn: "contact_name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "scenario", sourceLocation: "attributes", expectedColumn: "scenario", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "status", sourceLocation: "attributes", expectedColumn: "status", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "gtb_ref_no", sourceLocation: "attributes", expectedColumn: "gtb_ref_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "gtb_registration_no", sourceLocation: "attributes", expectedColumn: "gtb_registration_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "gtb_export_date", sourceLocation: "attributes", expectedColumn: "gtb_export_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "response_note", sourceLocation: "attributes", expectedColumn: "response_note", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "is_expired", sourceLocation: "attributes", expectedColumn: "is_expired", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "is_answerable", sourceLocation: "attributes", expectedColumn: "is_answerable", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "item_type", sourceLocation: "attributes", expectedColumn: "item_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_invoices", attribute: "invoice_parasut_id", sourceLocation: "relationships", expectedColumn: "invoice_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "printed_at", sourceLocation: "attributes", expectedColumn: "printed_at", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "uuid", sourceLocation: "attributes", expectedColumn: "uuid", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "vkn", sourceLocation: "attributes", expectedColumn: "vkn", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "invoice_number", sourceLocation: "attributes", expectedColumn: "invoice_number", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "is_printed", sourceLocation: "attributes", expectedColumn: "is_printed", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "pdf_url", sourceLocation: "attributes", expectedColumn: "pdf_url", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "e_smms", attribute: "sales_invoice_parasut_id", sourceLocation: "relationships", expectedColumn: "sales_invoice_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "balance", sourceLocation: "attributes", expectedColumn: "balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "trl_balance", sourceLocation: "attributes", expectedColumn: "trl_balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "usd_balance", sourceLocation: "attributes", expectedColumn: "usd_balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "eur_balance", sourceLocation: "attributes", expectedColumn: "eur_balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "gbp_balance", sourceLocation: "attributes", expectedColumn: "gbp_balance", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "email", sourceLocation: "attributes", expectedColumn: "email", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "iban", sourceLocation: "attributes", expectedColumn: "iban", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "managed_by_user_parasut_id", sourceLocation: "relationships", expectedColumn: "managed_by_user_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "employees", attribute: "managed_by_user_role_parasut_id", sourceLocation: "relationships", expectedColumn: "managed_by_user_role_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "inventory_levels", attribute: "stock_count", sourceLocation: "attributes", expectedColumn: "stock_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "inventory_levels", attribute: "initial_stock_count", sourceLocation: "attributes", expectedColumn: "initial_stock_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "inventory_levels", attribute: "critical_stock_count", sourceLocation: "attributes", expectedColumn: "critical_stock_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "inventory_levels", attribute: "product_parasut_id", sourceLocation: "relationships", expectedColumn: "product_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "inventory_levels", attribute: "warehouse_parasut_id", sourceLocation: "relationships", expectedColumn: "warehouse_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "full_path", sourceLocation: "attributes", expectedColumn: "full_path", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "bg_color", sourceLocation: "attributes", expectedColumn: "bg_color", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "text_color", sourceLocation: "attributes", expectedColumn: "text_color", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "category_type", sourceLocation: "attributes", expectedColumn: "category_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "parent_id", sourceLocation: "attributes", expectedColumn: "parent_id", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "parent_category_parasut_id", sourceLocation: "relationships", expectedColumn: "parent_category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "item_categories", attribute: "subcategories", sourceLocation: "relationships", expectedColumn: "subcategories", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "payments", attribute: "date", sourceLocation: "attributes", expectedColumn: "date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "payments", attribute: "amount", sourceLocation: "attributes", expectedColumn: "amount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "payments", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "payments", attribute: "notes", sourceLocation: "attributes", expectedColumn: "notes", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "payments", attribute: "payable_parasut_id", sourceLocation: "relationships", expectedColumn: "payable_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "payments", attribute: "transaction_parasut_id", sourceLocation: "relationships", expectedColumn: "transaction_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "sales_excise_duty_code", sourceLocation: "attributes", expectedColumn: "sales_excise_duty_code", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "sales_invoice_details_count", sourceLocation: "attributes", expectedColumn: "sales_invoice_details_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "purchase_invoice_details_count", sourceLocation: "attributes", expectedColumn: "purchase_invoice_details_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "list_price_in_trl", sourceLocation: "attributes", expectedColumn: "list_price_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "buying_price_in_trl", sourceLocation: "attributes", expectedColumn: "buying_price_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "stock_count", sourceLocation: "attributes", expectedColumn: "stock_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "code", sourceLocation: "attributes", expectedColumn: "code", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "vat_rate", sourceLocation: "attributes", expectedColumn: "vat_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "sales_excise_duty", sourceLocation: "attributes", expectedColumn: "sales_excise_duty", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "sales_excise_duty_type", sourceLocation: "attributes", expectedColumn: "sales_excise_duty_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "purchase_excise_duty", sourceLocation: "attributes", expectedColumn: "purchase_excise_duty", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "purchase_excise_duty_type", sourceLocation: "attributes", expectedColumn: "purchase_excise_duty_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "unit", sourceLocation: "attributes", expectedColumn: "unit", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "communications_tax_rate", sourceLocation: "attributes", expectedColumn: "communications_tax_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "list_price", sourceLocation: "attributes", expectedColumn: "list_price", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "buying_price", sourceLocation: "attributes", expectedColumn: "buying_price", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "buying_currency", sourceLocation: "attributes", expectedColumn: "buying_currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "inventory_tracking", sourceLocation: "attributes", expectedColumn: "inventory_tracking", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "products", attribute: "initial_stock_count", sourceLocation: "attributes", expectedColumn: "initial_stock_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "products", attribute: "gtip", sourceLocation: "attributes", expectedColumn: "gtip", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "barcode", sourceLocation: "attributes", expectedColumn: "barcode", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "inventory_levels_parasut_id", sourceLocation: "relationships", expectedColumn: "inventory_levels_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "products", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "vat_withholding", sourceLocation: "attributes", expectedColumn: "vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "quantity", sourceLocation: "attributes", expectedColumn: "quantity", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "unit_price", sourceLocation: "attributes", expectedColumn: "unit_price", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "vat_rate", sourceLocation: "attributes", expectedColumn: "vat_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "vat_withholding_rate", sourceLocation: "attributes", expectedColumn: "vat_withholding_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "discount_type", sourceLocation: "attributes", expectedColumn: "discount_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "discount_value", sourceLocation: "attributes", expectedColumn: "discount_value", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "excise_duty_type", sourceLocation: "attributes", expectedColumn: "excise_duty_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "excise_duty_value", sourceLocation: "attributes", expectedColumn: "excise_duty_value", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "communications_tax_rate", sourceLocation: "attributes", expectedColumn: "communications_tax_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "warehouse_parasut_id", sourceLocation: "relationships", expectedColumn: "warehouse_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bill_details", attribute: "product_parasut_id", sourceLocation: "relationships", expectedColumn: "product_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_paid", sourceLocation: "attributes", expectedColumn: "total_paid", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "gross_total", sourceLocation: "attributes", expectedColumn: "gross_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_excise_duty", sourceLocation: "attributes", expectedColumn: "total_excise_duty", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_communications_tax", sourceLocation: "attributes", expectedColumn: "total_communications_tax", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_vat", sourceLocation: "attributes", expectedColumn: "total_vat", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_vat_withholding", sourceLocation: "attributes", expectedColumn: "total_vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_discount", sourceLocation: "attributes", expectedColumn: "total_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "total_invoice_discount", sourceLocation: "attributes", expectedColumn: "total_invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "remaining", sourceLocation: "attributes", expectedColumn: "remaining", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "remaining_in_trl", sourceLocation: "attributes", expectedColumn: "remaining_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "payment_status", sourceLocation: "attributes", expectedColumn: "payment_status", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "is_detailed", sourceLocation: "attributes", expectedColumn: "is_detailed", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "sharings_count", sourceLocation: "attributes", expectedColumn: "sharings_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "e_invoices_count", sourceLocation: "attributes", expectedColumn: "e_invoices_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "remaining_reimbursement", sourceLocation: "attributes", expectedColumn: "remaining_reimbursement", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "remaining_reimbursement_in_trl", sourceLocation: "attributes", expectedColumn: "remaining_reimbursement_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "item_type", sourceLocation: "attributes", expectedColumn: "item_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "due_date", sourceLocation: "attributes", expectedColumn: "due_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "invoice_no", sourceLocation: "attributes", expectedColumn: "invoice_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "exchange_rate", sourceLocation: "attributes", expectedColumn: "exchange_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "withholding_rate", sourceLocation: "attributes", expectedColumn: "withholding_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "invoice_discount_type", sourceLocation: "attributes", expectedColumn: "invoice_discount_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "invoice_discount", sourceLocation: "attributes", expectedColumn: "invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "spender_parasut_id", sourceLocation: "relationships", expectedColumn: "spender_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "supplier_parasut_id", sourceLocation: "relationships", expectedColumn: "supplier_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "details", sourceLocation: "relationships", expectedColumn: "details", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "payments", sourceLocation: "relationships", expectedColumn: "payments", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "tags", sourceLocation: "relationships", expectedColumn: "tags", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "recurrence_plan_parasut_id", sourceLocation: "relationships", expectedColumn: "recurrence_plan_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "active_e_document_parasut_id", sourceLocation: "relationships", expectedColumn: "active_e_document_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "purchase_bills", attribute: "pay_to_parasut_id", sourceLocation: "relationships", expectedColumn: "pay_to_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "total_paid", sourceLocation: "attributes", expectedColumn: "total_paid", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "remaining", sourceLocation: "attributes", expectedColumn: "remaining", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "remaining_in_trl", sourceLocation: "attributes", expectedColumn: "remaining_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "due_date", sourceLocation: "attributes", expectedColumn: "due_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "exchange_rate", sourceLocation: "attributes", expectedColumn: "exchange_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "employee_parasut_id", sourceLocation: "relationships", expectedColumn: "employee_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "salaries", attribute: "tags", sourceLocation: "relationships", expectedColumn: "tags", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "vat_withholding", sourceLocation: "attributes", expectedColumn: "vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "quantity", sourceLocation: "attributes", expectedColumn: "quantity", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "unit_price", sourceLocation: "attributes", expectedColumn: "unit_price", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "vat_rate", sourceLocation: "attributes", expectedColumn: "vat_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "vat_withholding_rate", sourceLocation: "attributes", expectedColumn: "vat_withholding_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "discount_type", sourceLocation: "attributes", expectedColumn: "discount_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "discount_value", sourceLocation: "attributes", expectedColumn: "discount_value", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "excise_duty_type", sourceLocation: "attributes", expectedColumn: "excise_duty_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "excise_duty_value", sourceLocation: "attributes", expectedColumn: "excise_duty_value", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "communications_tax_rate", sourceLocation: "attributes", expectedColumn: "communications_tax_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "delivery_method", sourceLocation: "attributes", expectedColumn: "delivery_method", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "shipping_method", sourceLocation: "attributes", expectedColumn: "shipping_method", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "warehouse_parasut_id", sourceLocation: "relationships", expectedColumn: "warehouse_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoice_details", attribute: "product_parasut_id", sourceLocation: "relationships", expectedColumn: "product_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "invoice_no", sourceLocation: "attributes", expectedColumn: "invoice_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "gross_total", sourceLocation: "attributes", expectedColumn: "gross_total", expectedPgType: "numeric", currentlyMappedByProduction: true },
  { resource: "sales_invoices", attribute: "withholding", sourceLocation: "attributes", expectedColumn: "withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "total_excise_duty", sourceLocation: "attributes", expectedColumn: "total_excise_duty", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "total_communications_tax", sourceLocation: "attributes", expectedColumn: "total_communications_tax", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "total_vat", sourceLocation: "attributes", expectedColumn: "total_vat", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "total_vat_withholding", sourceLocation: "attributes", expectedColumn: "total_vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "total_discount", sourceLocation: "attributes", expectedColumn: "total_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "total_invoice_discount", sourceLocation: "attributes", expectedColumn: "total_invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "before_taxes_total", sourceLocation: "attributes", expectedColumn: "before_taxes_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "remaining", sourceLocation: "attributes", expectedColumn: "remaining", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "remaining_in_trl", sourceLocation: "attributes", expectedColumn: "remaining_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "payment_status", sourceLocation: "attributes", expectedColumn: "payment_status", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "item_type", sourceLocation: "attributes", expectedColumn: "item_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "due_date", sourceLocation: "attributes", expectedColumn: "due_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "invoice_series", sourceLocation: "attributes", expectedColumn: "invoice_series", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "invoice_id", sourceLocation: "attributes", expectedColumn: "invoice_id", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "exchange_rate", sourceLocation: "attributes", expectedColumn: "exchange_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "withholding_rate", sourceLocation: "attributes", expectedColumn: "withholding_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "invoice_discount_type", sourceLocation: "attributes", expectedColumn: "invoice_discount_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "invoice_discount", sourceLocation: "attributes", expectedColumn: "invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "billing_address", sourceLocation: "attributes", expectedColumn: "billing_address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "billing_postal_code", sourceLocation: "attributes", expectedColumn: "billing_postal_code", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "billing_phone", sourceLocation: "attributes", expectedColumn: "billing_phone", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "billing_fax", sourceLocation: "attributes", expectedColumn: "billing_fax", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "tax_office", sourceLocation: "attributes", expectedColumn: "tax_office", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "tax_number", sourceLocation: "attributes", expectedColumn: "tax_number", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "country", sourceLocation: "attributes", expectedColumn: "country", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "city", sourceLocation: "attributes", expectedColumn: "city", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "district", sourceLocation: "attributes", expectedColumn: "district", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "is_abroad", sourceLocation: "attributes", expectedColumn: "is_abroad", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "order_no", sourceLocation: "attributes", expectedColumn: "order_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "order_date", sourceLocation: "attributes", expectedColumn: "order_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "shipment_addres", sourceLocation: "attributes", expectedColumn: "shipment_addres", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "shipment_included", sourceLocation: "attributes", expectedColumn: "shipment_included", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "cash_sale", sourceLocation: "attributes", expectedColumn: "cash_sale", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "payer_tax_numbers", sourceLocation: "relationships", expectedColumn: "payer_tax_numbers", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "invoice_note", sourceLocation: "attributes", expectedColumn: "invoice_note", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "append_contact_balance", sourceLocation: "attributes", expectedColumn: "append_contact_balance", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "e_document_accounts", sourceLocation: "relationships", expectedColumn: "e_document_accounts", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "contact_parasut_id", sourceLocation: "relationships", expectedColumn: "contact_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "details", sourceLocation: "relationships", expectedColumn: "details", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "payments", sourceLocation: "relationships", expectedColumn: "payments", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "tags", sourceLocation: "relationships", expectedColumn: "tags", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "sales_offer_parasut_id", sourceLocation: "relationships", expectedColumn: "sales_offer_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "sharings", sourceLocation: "relationships", expectedColumn: "sharings", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "recurrence_plan_parasut_id", sourceLocation: "relationships", expectedColumn: "recurrence_plan_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_invoices", attribute: "active_e_document_parasut_id", sourceLocation: "relationships", expectedColumn: "active_e_document_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "content", sourceLocation: "attributes", expectedColumn: "content", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "contact_type", sourceLocation: "attributes", expectedColumn: "contact_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "sharings_count", sourceLocation: "attributes", expectedColumn: "sharings_count", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "status", sourceLocation: "attributes", expectedColumn: "status", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "display_exchange_rate_in_pdf", sourceLocation: "attributes", expectedColumn: "display_exchange_rate_in_pdf", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "gross_total", sourceLocation: "attributes", expectedColumn: "gross_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "withholding", sourceLocation: "attributes", expectedColumn: "withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_excise_duty", sourceLocation: "attributes", expectedColumn: "total_excise_duty", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_communications_tax", sourceLocation: "attributes", expectedColumn: "total_communications_tax", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_accommodation_tax", sourceLocation: "attributes", expectedColumn: "total_accommodation_tax", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_vat", sourceLocation: "attributes", expectedColumn: "total_vat", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_vat_withholding", sourceLocation: "attributes", expectedColumn: "total_vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "vat_withholding", sourceLocation: "attributes", expectedColumn: "vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_discount", sourceLocation: "attributes", expectedColumn: "total_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "total_invoice_discount", sourceLocation: "attributes", expectedColumn: "total_invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "due_date", sourceLocation: "attributes", expectedColumn: "due_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "currency", sourceLocation: "attributes", expectedColumn: "currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "exchange_rate", sourceLocation: "attributes", expectedColumn: "exchange_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "withholding_rate", sourceLocation: "attributes", expectedColumn: "withholding_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "invoice_discount_type", sourceLocation: "attributes", expectedColumn: "invoice_discount_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "invoice_discount", sourceLocation: "attributes", expectedColumn: "invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "billing_address", sourceLocation: "attributes", expectedColumn: "billing_address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "billing_phone", sourceLocation: "attributes", expectedColumn: "billing_phone", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "billing_fax", sourceLocation: "attributes", expectedColumn: "billing_fax", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "tax_office", sourceLocation: "attributes", expectedColumn: "tax_office", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "tax_number", sourceLocation: "attributes", expectedColumn: "tax_number", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "city", sourceLocation: "attributes", expectedColumn: "city", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "district", sourceLocation: "attributes", expectedColumn: "district", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "is_abroad", sourceLocation: "attributes", expectedColumn: "is_abroad", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "order_no", sourceLocation: "attributes", expectedColumn: "order_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "order_date", sourceLocation: "attributes", expectedColumn: "order_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "sales_invoice_parasut_id", sourceLocation: "relationships", expectedColumn: "sales_invoice_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "contact_parasut_id", sourceLocation: "relationships", expectedColumn: "contact_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "details", sourceLocation: "relationships", expectedColumn: "details", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "activities", sourceLocation: "relationships", expectedColumn: "activities", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_offers", attribute: "sharings", sourceLocation: "relationships", expectedColumn: "sharings", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "unit_price", sourceLocation: "attributes", expectedColumn: "unit_price", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "vat_rate", sourceLocation: "attributes", expectedColumn: "vat_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "quantity", sourceLocation: "attributes", expectedColumn: "quantity", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "discount_type", sourceLocation: "attributes", expectedColumn: "discount_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "discount_value", sourceLocation: "attributes", expectedColumn: "discount_value", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "communications_tax_rate", sourceLocation: "attributes", expectedColumn: "communications_tax_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "excise_duty_type", sourceLocation: "attributes", expectedColumn: "excise_duty_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "invoice_discount", sourceLocation: "attributes", expectedColumn: "invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "excise_duty", sourceLocation: "attributes", expectedColumn: "excise_duty", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "excise_duty_rate", sourceLocation: "attributes", expectedColumn: "excise_duty_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "discount", sourceLocation: "attributes", expectedColumn: "discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "communications_tax", sourceLocation: "attributes", expectedColumn: "communications_tax", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "detail_no", sourceLocation: "attributes", expectedColumn: "detail_no", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "net_total_without_invoice_discount", sourceLocation: "attributes", expectedColumn: "net_total_without_invoice_discount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "vat_withholding", sourceLocation: "attributes", expectedColumn: "vat_withholding", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "vat_withholding_rate", sourceLocation: "attributes", expectedColumn: "vat_withholding_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "accommodation_tax_rate", sourceLocation: "attributes", expectedColumn: "accommodation_tax_rate", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "accommodation_tax", sourceLocation: "attributes", expectedColumn: "accommodation_tax", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "accommodation_tax_exempt", sourceLocation: "attributes", expectedColumn: "accommodation_tax_exempt", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "excise_duty_value", sourceLocation: "attributes", expectedColumn: "excise_duty_value", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "sales_offers_details", attribute: "product_parasut_id", sourceLocation: "relationships", expectedColumn: "product_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "invoice_no", sourceLocation: "attributes", expectedColumn: "invoice_no", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "print_note", sourceLocation: "attributes", expectedColumn: "print_note", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "printed_at", sourceLocation: "attributes", expectedColumn: "printed_at", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "inflow", sourceLocation: "attributes", expectedColumn: "inflow", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "city", sourceLocation: "attributes", expectedColumn: "city", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "district", sourceLocation: "attributes", expectedColumn: "district", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "address", sourceLocation: "attributes", expectedColumn: "address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "shipment_date", sourceLocation: "attributes", expectedColumn: "shipment_date", expectedPgType: "timestamptz", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "procurement_number", sourceLocation: "attributes", expectedColumn: "procurement_number", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "contact_parasut_id", sourceLocation: "relationships", expectedColumn: "contact_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "tags", sourceLocation: "relationships", expectedColumn: "tags", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "stock_movements", sourceLocation: "relationships", expectedColumn: "stock_movements", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "shipment_documents", attribute: "invoices", sourceLocation: "relationships", expectedColumn: "invoices", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "detail_no", sourceLocation: "attributes", expectedColumn: "detail_no", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "date", sourceLocation: "attributes", expectedColumn: "date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "quantity", sourceLocation: "attributes", expectedColumn: "quantity", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "warehouse_parasut_id", sourceLocation: "relationships", expectedColumn: "warehouse_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "product_parasut_id", sourceLocation: "relationships", expectedColumn: "product_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "source_parasut_id", sourceLocation: "relationships", expectedColumn: "source_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "stock_movements", attribute: "contact_parasut_id", sourceLocation: "relationships", expectedColumn: "contact_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "stock_update_details", attribute: "old_total_inventory", sourceLocation: "attributes", expectedColumn: "old_total_inventory", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "stock_update_details", attribute: "new_total_inventory", sourceLocation: "attributes", expectedColumn: "new_total_inventory", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "stock_update_details", attribute: "warehouse_parasut_id", sourceLocation: "relationships", expectedColumn: "warehouse_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "stock_update_details", attribute: "product_parasut_id", sourceLocation: "relationships", expectedColumn: "product_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "stock_updates", attribute: "details", sourceLocation: "relationships", expectedColumn: "details", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "tags", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "total_paid", sourceLocation: "attributes", expectedColumn: "total_paid", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "remaining", sourceLocation: "attributes", expectedColumn: "remaining", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "remaining_in_trl", sourceLocation: "attributes", expectedColumn: "remaining_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "issue_date", sourceLocation: "attributes", expectedColumn: "issue_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "due_date", sourceLocation: "attributes", expectedColumn: "due_date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "net_total", sourceLocation: "attributes", expectedColumn: "net_total", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "category_parasut_id", sourceLocation: "relationships", expectedColumn: "category_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "taxes", attribute: "tags", sourceLocation: "relationships", expectedColumn: "tags", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "trackable_jobs", attribute: "status", sourceLocation: "attributes", expectedColumn: "status", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "trackable_jobs", attribute: "errors", sourceLocation: "attributes", expectedColumn: "errors", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "description", sourceLocation: "attributes", expectedColumn: "description", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "transaction_type", sourceLocation: "attributes", expectedColumn: "transaction_type", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "date", sourceLocation: "attributes", expectedColumn: "date", expectedPgType: "date", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "amount_in_trl", sourceLocation: "attributes", expectedColumn: "amount_in_trl", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "debit_amount", sourceLocation: "attributes", expectedColumn: "debit_amount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "debit_currency", sourceLocation: "attributes", expectedColumn: "debit_currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "credit_amount", sourceLocation: "attributes", expectedColumn: "credit_amount", expectedPgType: "numeric", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "credit_currency", sourceLocation: "attributes", expectedColumn: "credit_currency", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "debit_account_parasut_id", sourceLocation: "relationships", expectedColumn: "debit_account_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "credit_account_parasut_id", sourceLocation: "relationships", expectedColumn: "credit_account_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "transactions", attribute: "payments", sourceLocation: "relationships", expectedColumn: "payments", expectedPgType: "jsonb", currentlyMappedByProduction: false },
  { resource: "warehouses", attribute: "name", sourceLocation: "attributes", expectedColumn: "name", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "warehouses", attribute: "address", sourceLocation: "attributes", expectedColumn: "address", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "warehouses", attribute: "city", sourceLocation: "attributes", expectedColumn: "city", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "warehouses", attribute: "district", sourceLocation: "attributes", expectedColumn: "district", expectedPgType: "text", currentlyMappedByProduction: false },
  { resource: "warehouses", attribute: "is_abroad", sourceLocation: "attributes", expectedColumn: "is_abroad", expectedPgType: "boolean", currentlyMappedByProduction: false },
  { resource: "warehouses", attribute: "inventory_levels_parasut_id", sourceLocation: "relationships", expectedColumn: "inventory_levels_parasut_id", expectedPgType: "text", currentlyMappedByProduction: false },
];

export const REGISTRY_RESOURCES: readonly string[] = [
  "accounts",
  "bank_fees",
  "contacts",
  "e_archives",
  "e_invoice_inboxes",
  "e_invoices",
  "e_smms",
  "employees",
  "inventory_levels",
  "item_categories",
  "payments",
  "products",
  "purchase_bill_details",
  "purchase_bills",
  "salaries",
  "sales_invoice_details",
  "sales_invoices",
  "sales_offers",
  "sales_offers_details",
  "shipment_documents",
  "stock_movements",
  "stock_update_details",
  "stock_updates",
  "tags",
  "taxes",
  "trackable_jobs",
  "transactions",
  "warehouses",
];
