import {
  BarChart3,
  Bell,
  Boxes,
  Calculator,
  ClipboardList,
  Factory,
  FileStack,
  FileText,
  Globe2,
  HandCoins,
  Handshake,
  LayoutDashboard,
  Activity,
  Package,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  StickyNote,
  Truck,
  UserCog,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ErpModuleStatus = "active" | "beta" | "soon";

export type ErpModuleConfig = {
  id: string;
  title: string;
  description: string;
  path: string;
  icon: LucideIcon;
  status: ErpModuleStatus;
  requiredPermission?: string;
  visible?: boolean;
};

export const erpModules: ErpModuleConfig[] = [
  {
    id: "dashboard",
    title: "Kontrol Paneli",
    description: "Günlük operasyon özeti ve hızlı erişimler",
    path: "/dashboard",
    icon: LayoutDashboard,
    status: "active",
    requiredPermission: "dashboard.view",
  },
  {
    id: "customers",
    title: "Müşteriler",
    description: "Müşteri cari kartları, finans bakiyesi ve ilişki takibi",
    path: "/musteriler",
    icon: Users,
    status: "active",
    requiredPermission: "crm.view",
  },
  {
    id: "suppliers",
    title: "Tedarikçiler",
    description: "Tedarikçi kartları, satın alma ve ödeme takibi",
    path: "/tedarikciler",
    icon: Handshake,
    status: "active",
    requiredPermission: "crm.view",
  },
  {
    id: "erp",
    title: "ERP",
    description: "Üretim, stok, kalite ve sevkiyat yönetimi",
    path: "/",
    icon: Factory,
    status: "active",
    requiredPermission: "production.view",
    visible: false,
  },
  {
    id: "quotations",
    title: "Teklifler",
    description: "Teklif oluşturma, PDF, e-posta ve WhatsApp akışı",
    path: "/teklifler",
    icon: FileText,
    status: "active",
    requiredPermission: "sales.view",
  },
  {
    id: "orders",
    title: "Siparişler",
    description: "Satış siparişleri ve iş emri dönüşümleri",
    path: "/siparisler",
    icon: ShoppingCart,
    status: "active",
    requiredPermission: "sales.view",
  },
  {
    id: "finance",
    title: "Finans",
    description: "Cari hesap, ödeme ve resmi/operasyonel takip",
    path: "/finans",
    icon: Wallet,
    status: "active",
    requiredPermission: "finance.view",
  },
  {
    id: "cargo",
    title: "Kargo",
    description: "Müşteri bazlı kargo etiketi ve PDF çıktısı",
    path: "/kargo",
    icon: Package,
    status: "active",
    requiredPermission: "inventory.view",
  },
  {
    id: "calculator",
    title: "Hesaplama",
    description: "Dişli hesaplama ve üretim reçetesi araçları",
    path: "/calculator",
    icon: Calculator,
    status: "active",
    requiredPermission: "production.view",
  },
  {
    id: "notifications",
    title: "Bildirimler",
    description: "Sistem uyarıları ve işlem geçmişi",
    path: "/bildirimler",
    icon: Bell,
    status: "active",
    requiredPermission: "dashboard.view",
  },
  {
    id: "health",
    title: "Sağlık Merkezi",
    description: "Operasyon sağlığı, uyarılar ve platform olayları",
    path: "/health",
    icon: Activity,
    status: "active",
    requiredPermission: "reports.view",
  },
  {
    id: "tasks",
    title: "Görevler",
    description: "Atanan işler ve takip listesi",
    path: "/gorevler",
    icon: ClipboardList,
    status: "soon",
    requiredPermission: "dashboard.view",
  },
  {
    id: "notes",
    title: "Notlar",
    description: "Operasyon notları ve iç kayıtlar",
    path: "/notlar",
    icon: StickyNote,
    status: "soon",
    requiredPermission: "dashboard.view",
  },
  {
    id: "settings",
    title: "Ayarlar",
    description: "ERP yapılandırma ve sistem ayarları",
    path: "/ayarlar",
    icon: Settings,
    status: "active",
    requiredPermission: "settings.view",
  },
  {
    id: "logistics",
    title: "Sevkiyat",
    description: "ERP sevkiyat ve lojistik kayıtları",
    path: "/logistics",
    icon: Truck,
    status: "active",
    requiredPermission: "production.view",
    visible: false,
  },
  {
    id: "production-module",
    title: "Üretim",
    description: "İş emirleri, rotalar ve üretim operasyonları",
    path: "/production",
    icon: Factory,
    status: "active",
    requiredPermission: "production.view",
  },
  {
    id: "inventory-module",
    title: "Stok Yönetimi",
    description: "Malzeme, ürün ve depo hareketleri",
    path: "/inventory",
    icon: Boxes,
    status: "active",
    requiredPermission: "inventory.view",
  },
  {
    id: "purchasing-module",
    title: "Satın Alma",
    description: "Satın alma siparişleri ve tedarik akışı",
    path: "/purchasing",
    icon: HandCoins,
    status: "active",
    requiredPermission: "purchasing.view",
  },
  {
    id: "quality-module",
    title: "Kalite Yönetimi",
    description: "Kalite raporları, ölçümler ve kontrol kayıtları",
    path: "/quality",
    icon: ShieldCheck,
    status: "active",
    requiredPermission: "quality.view",
  },
  {
    id: "maintenance-module",
    title: "Bakım Yönetimi",
    description: "Makine bakım planları ve arıza kayıtları",
    path: "/maintenance",
    icon: Wrench,
    status: "active",
    requiredPermission: "maintenance.view",
  },
  {
    id: "hr-module",
    title: "İnsan Kaynakları",
    description: "Personel kayıtları ve çalışma süreleri",
    path: "/hr",
    icon: UserCog,
    status: "active",
    requiredPermission: "hr.view",
  },
  {
    id: "website-module",
    title: "Web Sitesi",
    description: "Site içeriği, ürün görünürlüğü ve yönetim ekranları",
    path: "/website",
    icon: Globe2,
    status: "active",
    requiredPermission: "website.view",
  },
  {
    id: "commerce-module",
    title: "E-Ticaret",
    description: "Mağaza siparişleri, ürün katalogları ve satış akışı",
    path: "/commerce",
    icon: ShoppingBag,
    status: "active",
    requiredPermission: "commerce.view",
  },
  {
    id: "reports-module",
    title: "Raporlar",
    description: "Yönetim, finans, üretim ve stok raporları",
    path: "/reports",
    icon: BarChart3,
    status: "active",
    requiredPermission: "reports.view",
  },
  {
    id: "documents-module",
    title: "Dokümanlar",
    description: "Operasyon dokümanları ve dosya kayıtları",
    path: "/documents",
    icon: FileStack,
    status: "active",
    requiredPermission: "production.view",
  },
];

export const visibleErpModules = erpModules.filter((module) => module.visible !== false);

export const dashboardModuleIds = ["customers", "suppliers", "quotations", "calculator", "orders", "cargo", "finance", "notifications", "health"];

export const dashboardModules = visibleErpModules.filter((module) => dashboardModuleIds.includes(module.id));
