import type { SalesActivity, SalesOrder, SalesQuote } from "./salesTypes";
export const salesQuotes: SalesQuote[] = [
  {
    id: "q-92",
    no: "TKL-2026-0092",
    customerId: "atlas-makine",
    contactId: "atlas-mert",
    contact: "Mert Aydın",
    projectId: "project-red",
    project: "Redüktör Modernizasyonu",
    subject: "Redüktör dişli seti üretimi",
    currency: "TRY",
    created: "08.07.2026",
    validUntil: "31.07.2026",
    status: "Siparişe Dönüştürüldü",
    lines: [
      {
        productServiceId: "p1",
        code: "HD-M2-001",
        name: "Helisel Dişli M2",
        material: "42CrMo4",
        quantity: 24,
        unit: "Adet",
        unitPrice: 14500,
        discount: 0,
        vat: 20,
      },
    ],
    notes: "Teknik resme uygun üretim.",
    paymentTerms: "%40 avans, bakiye teslimde",
    deliveryTerms: "Dayan Dişli fabrika teslim",
    linkedOrderNo: "SIP-2026-0072",
  },
  {
    id: "q-78",
    no: "TKL-2026-0078",
    customerId: "eksen-otomotiv",
    contactId: "eksen-derya",
    contact: "Derya Koç",
    projectId: "project-konik",
    project: "Konik Dişli Serisi",
    subject: "Konik dişli seri üretimi",
    currency: "TRY",
    created: "18.06.2026",
    validUntil: "30.07.2026",
    status: "Beklemede",
    lines: [
      {
        productServiceId: "p2",
        code: "KD-S-014",
        name: "Konik Dişli Seti",
        material: "16MnCr5",
        quantity: 50,
        unit: "Adet",
        unitPrice: 2490,
        discount: 5,
        vat: 20,
      },
    ],
    notes: "Numune onayı sonrası seri üretim.",
    paymentTerms: "30 gün vadeli",
    deliveryTerms: "Müşteri adresi",
  },
];
export const salesOrders: SalesOrder[] = [
  {
    id: "o-72",
    no: "SIP-2026-0072",
    customerId: "atlas-makine",
    sourceQuoteId: "q-92",
    sourceQuoteNo: "TKL-2026-0092",
    project: "Redüktör Modernizasyonu",
    orderDate: "16.07.2026",
    dueDate: "05.08.2026",
    total: "₺417.600",
    status: "Üretime Aktarıldı",
  },
  {
    id: "o-68",
    no: "SIP-2026-0068",
    customerId: "eksen-otomotiv",
    project: "Konik Dişli Serisi",
    orderDate: "10.07.2026",
    dueDate: "28.07.2026",
    total: "₺186.500",
    status: "Onaylandı",
  },
];
export const salesActivities: SalesActivity[] = [
  {
    id: "a1",
    date: "16.07.2026",
    type: "Toplantı",
    customerId: "atlas-makine",
    quoteId: "q-92",
    relation: "TKL-2026-0092",
    description: "Teknik şartlar ve termin görüşüldü.",
    owner: "Bora Yılmaz",
    status: "Tamamlandı",
  },
  {
    id: "a2",
    date: "18.07.2026",
    type: "Takip",
    customerId: "eksen-otomotiv",
    quoteId: "q-78",
    relation: "TKL-2026-0078",
    description: "Teklif geri bildirimi alınacak.",
    owner: "Ebru Demir",
    status: "Planlandı",
  },
];
export const salesSubmenu = [
  {
    id: "quotes",
    label: "Teklifler",
    route: "/apps/sales/quotes",
  },
  {
    id: "orders",
    label: "Siparişler",
    route: "/apps/sales/orders",
  },
  {
    id: "activities",
    label: "Satış Faaliyetleri",
    route: "/apps/sales/activities",
  },
];
