// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_KEY);
export const SUPABASE_ENV_ERROR =
  "Supabase env eksik: VITE_SUPABASE_URL ve VITE_SUPABASE_PUBLISHABLE_KEY gerekli.";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createDisabledSupabaseClient(): SupabaseClient<Database> {
  return new Proxy(
    {},
    {
      get() {
        throw new Error(SUPABASE_ENV_ERROR);
      },
    }
  ) as SupabaseClient<Database>;
}

export const supabase = isSupabaseConfigured ? createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}) : createDisabledSupabaseClient();
